var express = require('express');
var router = express.Router();
var mongoose = require('mongoose');
var Field = mongoose.model('Field');
var axios = require('axios');
var config = require('../config.json');

// form post route
router.post('/addpost', function(req, res) {
        
    var field = new Field();
    field.name = req.body.name;
    field.number = req.body.number;
    field.email = req.body.email;
    
    if( !field.name || !field.number || !field.email ){
        return res.status(403).send('Bad request');
    }
    field.save(function (err, doc) {
        if(err){
            return res.status(500).send(err);
        }        
        
        // add to prosperworks if email matches
        if(isGmailOrYahoo(req.body.email)){
            //send automated mail
            var nodemailer = require('nodemailer');
            //var smtpTransport = require('nodemailer-smtp-transport');

            var transporter = nodemailer.createTransport({
                service: 'gmail',
                host: 'smtp.gmail.com',
                auth: {
                    type: 'OAuth2',
                    user: config.prosperworks.userEmail,
                    clientId: config.gmail.clientId,
                    clientSecret: config.gmail.clientSecret,
                    refreshToken: config.gmail.refreshToken,                                
                    accessToken: config.gmail.accessToken                    
                }
            });

            var mailOptions = {
                from: config.prosperworks.userEmail,
                to: req.body.email,
                subject: 'Sending autogenerated mail',
                text: 'Hello have a nice day!'
            };

            transporter.sendMail(mailOptions, function(error, info){
                if (error) {
                    console.log(error);
                    return res.status(500).send('Mail not sent');
                } else {
                    console.log('Email sent: ' + info.response);
                    return res.status(200).send('Mail sent');
                }
            });            
        } else {
            //push to PW
            var payload = {
                "name": req.body.name,
                "email": {
                    "email": req.body.email,
                    "category":"work"
                },
                "phone_numbers": [
                    {
                        "number": req.body.number,
                        "category":"mobile"
                    }
                ]               
            };
            
            var pwconfig = {
                "headers": {
                    "X-PW-AccessToken": config.prosperworks.apiKey,
                    "X-PW-Application": config.prosperworks.application,
                    "X-PW-UserEmail": config.prosperworks.userEmail,
                    "Content-Type": "application/json"                    
                } 
            }; 
            axios.post('https://api.prosperworks.com/developer_api/v1/leads', payload, pwconfig)
            .then(function(response){
                return res.status(200).send('Added record to PW');
            })
            .catch(function(error){
                console.log(error);
                return res.status(500).send('Error adding record to PW');
            });            
        }
    });    
});

module.exports = router;

var isGmailOrYahoo = function(mailaddr) {
    return mailaddr.endsWith('@gmail.com') || mailaddr.endsWith('@yahoo.com');
};


